#!/usr/bin/env python3
"""Refresh optional routing pointers. Does not embed personal or brand content."""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def replace_section(text, marker, content):
    start = f"<!-- BEGIN:{marker}"
    end = f"<!-- END:{marker} -->"
    if text.count(start) != text.count(end) or text.count(start) > 1:
        raise ValueError(f"Malformed generated section: {marker}")
    block = (
        f"<!-- BEGIN:{marker} (generated by scripts/compose.py, do not hand-edit) -->\n"
        f"{content.strip()}\n{end}"
    )
    pattern = re.compile(rf"<!-- BEGIN:{re.escape(marker)}.*?{re.escape(end)}", re.S)
    if start in text:
        if not pattern.search(text):
            raise ValueError(f"Malformed generated section: {marker}")
        return pattern.sub(lambda _: block, text)
    return text.rstrip() + "\n\n" + block + "\n"


def compose(root):
    root = pathlib.Path(root).resolve()
    manual = root / "AGENTS.md"
    if not (root / "memory" / "MEMORY.md").is_file():
        raise ValueError("Missing memory/MEMORY.md; restore the live index first.")
    text = manual.read_text(encoding="utf-8")
    memory = (
        "## Memory pointer\n\n"
        "Read [the memory index](memory/MEMORY.md), then open relevant memory files. "
        "Their contents are not embedded here."
    )
    pin_file = root / "companies" / ".pinned"
    slug = pin_file.read_text(encoding="utf-8").strip() if pin_file.exists() else ""
    if slug:
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):
            raise ValueError("Invalid default brand slug in companies/.pinned.")
        brand = root / "companies" / slug
        if not brand.resolve().is_relative_to(root / "companies"):
            raise ValueError("Default brand resolves outside companies/.")
        for name in ("facts.md", "flavor.md"):
            if not (brand / name).is_file():
                raise ValueError(f"Missing companies/{slug}/{name}; repair the profile first.")
        primary = (
            f"## Default brand pointer\n\n"
            f"Default: [{slug}](companies/{slug}/facts.md). "
            f"Read its [voice evidence](companies/{slug}/flavor.md) and scoped rules when relevant. "
            "The task's explicit brand wins. Recheck companies/.pinned for the current default."
        )
    else:
        primary = (
            "## Default brand pointer\n\n"
            "No default brand cached. Read companies/.pinned if it exists; "
            "otherwise use the brand established by the user's task."
        )
    result = replace_section(text, "MEMORY-INDEX", memory)
    result = replace_section(result, "PINNED-BRAND", primary)
    if result != text:
        manual.write_text(result, encoding="utf-8", newline="\n")
    return result != text


if __name__ == "__main__":
    try:
        changed = compose(ROOT)
    except (OSError, ValueError) as error:
        print(f"Pointer refresh failed: {error}", file=sys.stderr)
        sys.exit(1)
    print("Routing pointers refreshed." if changed else "Routing pointers already current.")
